# Generated by Django 3.0.5 on 2020-11-30 16:42

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=300)),
                ('description', models.TextField(default=None)),
                ('instructions', models.TextField(default=None)),
                ('ingredients', models.TextField(default=None)),
                ('course_type', models.CharField(default=None, max_length=150)),
                ('difficulty', models.CharField(max_length=100)),
                ('cooking_method', models.CharField(default=None, max_length=150)),
                ('cost', models.CharField(max_length=100)),
                ('is_vegetarian', models.BooleanField(null=True)),
            ],
        ),
    ]
