# Generated by Django 3.0.5 on 2020-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="image_url",
            field=models.URLField(default=None),
        ),
    ]
