# Generated by Django 3.0.5 on 2020-11-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201129_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='instruction',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
